apiVersion: batch/v1
kind: CronJob
metadata:
  name: stepcd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
          - name: zad2gitops
            image: zomsik/zad2gitops:latest
            command: [sh, -e, -c]
            args:
              - git clone https://github.com/zomsik/config-repo /tmp/ && find /tmp/ -name '*.yaml' -exec kubectl apply -f {} \;